import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    PrefUtils().setThemeData(_newTheme);
    Get.forceAppUpdate();
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.blue5001,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: colorScheme.primary,
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(19.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        side: BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.gray300,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.black900,
          fontSize: 16.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: appTheme.gray80001,
          fontSize: 13.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: 11.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w400,
        ),
        displaySmall: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: 39.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w600,
        ),
        headlineLarge: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: 33.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w600,
        ),
        headlineMedium: TextStyle(
          color: colorScheme.primary,
          fontSize: 27.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w500,
        ),
        labelLarge: TextStyle(
          color: appTheme.gray80001,
          fontSize: 13.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w600,
        ),
        labelMedium: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: 11.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w500,
        ),
        titleLarge: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: 23.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: 19.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w600,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF373BC8),
    primaryContainer: Color(0XFFE6E6E6),
    secondary: Color(0XFFE6E6E6),
    secondaryContainer: Color(0X7F373BC8),
    tertiary: Color(0XFFE6E6E6),
    tertiaryContainer: Color(0X7F373BC8),

    // Background colors
    background: Color(0XFFE6E6E6),

    // Surface colors
    surface: Color(0XFFE6E6E6),
    surfaceTint: Color(0X33FFFFFF),
    surfaceVariant: Color(0X7F373BC8),

    // Error colors
    error: Color(0X33FFFFFF),
    errorContainer: Color(0XFF42489B),
    onError: Color(0XFF2A2A2A),
    onErrorContainer: Color(0X33FFFFFF),

    // On colors(text colors)
    onBackground: Color(0XFF292929),
    onInverseSurface: Color(0XFF2A2A2A),
    onPrimary: Color(0X33FFFFFF),
    onPrimaryContainer: Color(0XFF292929),
    onSecondary: Color(0XFF292929),
    onSecondaryContainer: Color(0X33FFFFFF),
    onTertiary: Color(0XFF292929),
    onTertiaryContainer: Color(0X33FFFFFF),

    // Other colors
    outline: Color(0X33FFFFFF),
    outlineVariant: Color(0XFFE6E6E6),
    scrim: Color(0XFFE6E6E6),
    shadow: Color(0X33FFFFFF),

    // Inverse colors
    inversePrimary: Color(0XFFE6E6E6),
    inverseSurface: Color(0X33FFFFFF),

    // Pending colors
    onSurface: Color(0XFF292929),
    onSurfaceVariant: Color(0X33FFFFFF),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  // Blue
  Color get blue200 => Color(0XFF89CAF7);
  Color get blue50 => Color(0XFFDCECFE);
  Color get blue5001 => Color(0XFFDCEBFE);
  Color get blue600 => Color(0XFF107EE4);
  Color get blue800 => Color(0XFF3474BA);

  // BlueGray
  Color get blueGray100 => Color(0XFFD9D9D9);
  Color get blueGray400 => Color(0XFF888888);

  // DeepPurple
  Color get deepPurple100 => Color(0XFFD4D5FC);
  Color get deepPurple500 => Color(0XFF6033BF);

  // Gray
  Color get gray200 => Color(0XFFEBEBEB);
  Color get gray300 => Color(0XFFDFDFDF);
  Color get gray30001 => Color(0XFFDEDDDD);
  Color get gray400 => Color(0XFFC0C0C0);
  Color get gray40001 => Color(0XFFAFAFAF);
  Color get gray40002 => Color(0XFFB9B9B9);
  Color get gray40003 => Color(0XFFBCBCBC);
  Color get gray50 => Color(0XFFFAFAFA);
  Color get gray500 => Color(0XFF979797);
  Color get gray800 => Color(0XFF3A3939);
  Color get gray80001 => Color(0XFF4B4B4B);
  Color get gray80002 => Color(0XFF393939);
  Color get gray900 => Color(0XFF222222);
  Color get gray90001 => Color(0XFF232323);
  Color get gray90002 => Color(0XFF1F1E1E);
  Color get gray90003 => Color(0XFF1C1B1F);

  // Indigo
  Color get indigo100 => Color(0XFFCCCDF5);
  Color get indigo10001 => Color(0XFFCCCDF4);
  Color get indigo600 => Color(0XFF3438C0);

  // LightBlue
  Color get lightBlue900 => Color(0XFF0A558F);

  // Lime
  Color get lime600 => Color(0XFFC8C437);

  // Teal
  Color get teal200 => Color(0XFF7EC3CF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
